-- V5-ADD-004: COBOL契約原簿から夜間複製する参照専用テーブル。
CREATE TABLE INQUIRY_SNAPSHOT (
    CONTRACT_NUMBER CHAR(10) PRIMARY KEY,
    STATUS_CODE CHAR(2) NULL,
    INSURED_AMOUNT DECIMAL(10, 0) NULL,
    AS_OF_DATE CHAR(8) NOT NULL
);

-- アプリケーションが使用するSQLは参照だけに限定する。
SELECT CONTRACT_NUMBER, STATUS_CODE, INSURED_AMOUNT, AS_OF_DATE
  FROM INQUIRY_SNAPSHOT
 WHERE CONTRACT_NUMBER = ?;
