-- V5: 照会用複製。原簿テーブルはこのDBに置かない。
CREATE TABLE INQUIRY_STATE (
  ID INTEGER PRIMARY KEY CHECK (ID=1), AS_OF DATE,
  CONTENT_HASH VARCHAR(64), RECORD_COUNT INTEGER NOT NULL CHECK (RECORD_COUNT>=0)
);
INSERT INTO INQUIRY_STATE VALUES (1,NULL,NULL,0);
CREATE TABLE INQUIRY_SNAPSHOT (
  APP_NUMBER CHAR(10) PRIMARY KEY,
  PRODUCT CHAR(2) NOT NULL CHECK (PRODUCT IN ('WL','MI','CI')),
  STATUS CHAR(2) CHECK (STATUS IN ('01','02','03','04','05','06','07','08','09')),
  AMOUNT DECIMAL(8,0) CHECK (AMOUNT>=0),
  RESPONSIBILITY_DATE DATE, PROCESS_DATE DATE, RECEIPT_DATE DATE,
  RULE_CODE CHAR(3) CHECK (RULE_CODE IN ('OLD','NEW','ERR')), APPLIED_DATE DATE,
  AS_OF DATE NOT NULL, REASON CHAR(3), APPROVAL CHAR(1)
);
-- 配布先管理者が資格情報を別途作成し、Webユーザーには次の2権限のみ付与する。
-- GRANT SELECT ON INQUIRY_STATE TO INQUIRY_WEB;
-- GRANT SELECT ON INQUIRY_SNAPSHOT TO INQUIRY_WEB;
-- 取込ユーザーには両表のSELECT/INSERT/UPDATE/DELETEを付与する。
