-- V6-ADD-016: 査定確定前の受付状態を保持するJava側テーブル。
CREATE TABLE ENTRY_APPLICATION (
    APPLICATION_NUMBER CHAR(10) PRIMARY KEY,
    PRODUCT_CODE CHAR(2) NOT NULL,
    AGE DECIMAL(3,0) NOT NULL,
    INSURED_AMOUNT DECIMAL(10,0) NOT NULL,
    STATUS_CODE VARCHAR(24) NOT NULL,
    RECEIVED_AT TIMESTAMP NOT NULL
);
CREATE INDEX IX_ENTRY_COBOL_EXPORT ON ENTRY_APPLICATION (STATUS_CODE, APPLICATION_NUMBER);
