-- V9-ADD-019: 元時刻とUTC正規化値を併記する監査イベント。
CREATE TABLE AUDIT_EVENT (
    AUDIT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR(24) NOT NULL,
    TRANSACTION_KEY VARCHAR(40) NOT NULL,
    OPERATOR_ID VARCHAR(32) NOT NULL,
    INPUT_DIGEST CHAR(32) NOT NULL,
    REASON_CODE VARCHAR(12) NOT NULL,
    ORIGINAL_TIME VARCHAR(32) NOT NULL,
    ORIGINAL_OFFSET VARCHAR(8) NOT NULL,
    OCCURRED_AT_UTC TIMESTAMP NOT NULL,
    UNIQUE (SOURCE_SYSTEM, TRANSACTION_KEY, ORIGINAL_TIME)
);
CREATE INDEX IX_AUDIT_CORRELATION ON AUDIT_EVENT (TRANSACTION_KEY, OCCURRED_AT_UTC);

-- V9-ADD-020: 共有DB保存後の発行要求を残すOutbox。
-- V9-FIX-002 ADD: 本人確認の業務結果。Outboxと同一トランザクションで登録する。
CREATE TABLE KYC_RESULT (
    TRANSACTION_KEY VARCHAR(40) PRIMARY KEY,
    RESULT_CODE VARCHAR(20) NOT NULL
);

CREATE TABLE KYC_OUTBOX (
    TRANSACTION_KEY VARCHAR(40) PRIMARY KEY,
    RESULT_CODE VARCHAR(20) NOT NULL,
    AUDIT_REASON VARCHAR(12) NOT NULL,
    PUBLISHED_FLAG CHAR(1) NOT NULL DEFAULT 'N',
    -- V9-FIX-002 ADD: 未発行再送順と発行完了を追跡する。
    CREATED_AT TIMESTAMP NOT NULL,
    PUBLISHED_AT TIMESTAMP NULL
);
CREATE INDEX IX_KYC_OUTBOX_PENDING ON KYC_OUTBOX (PUBLISHED_FLAG, CREATED_AT, TRANSACTION_KEY);
