-- V8-ADD-020: 接続先別の応答待ちと再送回数を保持する。
CREATE TABLE INTEGRATION_STATE (
    PARTNER_CODE VARCHAR(20) NOT NULL,
    TRANSACTION_ID VARCHAR(40) NOT NULL,
    APPLICATION_NUMBER CHAR(10) NOT NULL,
    REQUEST_PAYLOAD VARCHAR(2000) NOT NULL,
    -- V8-FIX-001 ADD: 初回受付時の順序を再送まで保持する。
    SEQUENCE_NUMBER DECIMAL(12,0) NOT NULL,
    STATUS_CODE VARCHAR(24) NOT NULL,
    RETRY_COUNT DECIMAL(3,0) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (PARTNER_CODE, TRANSACTION_ID)
);
-- V8-FIX-001 DEL: CREATE INDEX IX_INTEGRATION_RETRY ON INTEGRATION_STATE (STATUS_CODE, UPDATED_AT, TRANSACTION_ID);
-- V8-FIX-001 ADD: 再送検索を初回キュー番号順にする。
CREATE INDEX IX_INTEGRATION_RETRY ON INTEGRATION_STATE (STATUS_CODE, SEQUENCE_NUMBER);
