-- V8-FIX-001 ADD: 既存環境向け移行手順。
-- 1. 新規受付を停止し、RETRY_WAIT件数を運用記録と照合する。
-- 2. 初回受付キュー番号を保全記録から復元してからNOT NULL化する。
ALTER TABLE INTEGRATION_STATE ADD SEQUENCE_NUMBER DECIMAL(12,0);

-- 次のUPDATEは製品DBの採番表・保全記録に合わせて運用担当が実施する。
-- UPDATE INTEGRATION_STATE SET SEQUENCE_NUMBER = <保全済み初回キュー番号> WHERE ...;

ALTER TABLE INTEGRATION_STATE ALTER COLUMN SEQUENCE_NUMBER SET NOT NULL;
DROP INDEX IX_INTEGRATION_RETRY;
CREATE INDEX IX_INTEGRATION_RETRY ON INTEGRATION_STATE (STATUS_CODE, SEQUENCE_NUMBER);
