-- V7-ADD-015: Java内部モデルへチャネル所有情報を追加する。
ALTER TABLE ENTRY_APPLICATION ADD CHANNEL_CODE VARCHAR(16) NOT NULL DEFAULT 'EMPLOYEE';
ALTER TABLE ENTRY_APPLICATION ADD OWNER_AGENCY_ID CHAR(10) NULL;
CREATE INDEX IX_ENTRY_AGENCY ON ENTRY_APPLICATION (OWNER_AGENCY_ID, APPLICATION_NUMBER);

-- COBOL契約原簿は変更せず、80文字連携の予約領域を使用する。
